# Generated by Django 4.1.1 on 2023-01-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userFormation',
        ),
    ]
